name: CI

on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/github-hosted-runners-reference#standard-github-hosted-runners-for-public-repositories
        os:
          # Linux-arm64
          # - ubuntu-22.04-arm
          # - ubuntu-24.04-arm
          # Linux-x64
          - ubuntu-22.04
          - ubuntu-24.04
          # macOS-arm64
          - macos-14
          # - macos-15
          # - macos-26
          # macOS-x64
          # - macos-15-intel
        python_method:
          - devbox
          - pixi
          - flox
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_METHOD: ${{ matrix.python_method }}
      METHOD: ${{ matrix.python_method == 'flox' && 'flox' || 'devbox' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        if: env.METHOD == 'devbox'
        uses: jetify-com/devbox-install-action@v0.14.0
        with:
          enable-cache: true
      - name: Install Pixi
        if: matrix.python_method == 'pixi'
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          # separated by spaces
          environments: >-
            cython
            nuitka
            python
      - name: Install flox
        if: env.METHOD == 'flox'
        uses: flox/setup-flox@v3

      - name: Compilers version
        run: |
            if [ "${METHOD}" = "flox" ]; then
                flox activate --dir . -- make compiler_version
            else
                devbox run --config envs/system 'cd ../..; make compiler_version'
            fi

      - name: compile, run, and test
        run: |
            if [ "${METHOD}" = "flox" ]; then
                flox activate --dir . -- make all ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored=
            else
                devbox run --config envs/system 'cd ../..; make all ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='
            fi

      - name: show size and list dynamically linked libraries
        run: |
            if [ "${METHOD}" = "flox" ]; then
                flox activate --dir . -- make size list_link -j1
            else
                devbox run --config envs/system 'cd ../..; make size list_link -j1'
            fi
        
      - name: Benchmark
        run: |
            if [ "${METHOD}" = "flox" ]; then
                flox activate --dir . -- make bench_md ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored=
            else
                devbox run --config envs/system 'cd ../..; make bench_md ARGS_RUN_diffpath="/usr/local/bin:/usr/bin:/usr/sbin:/bin:/sbin $PATH" ARGS_BENCH_gitignored='
            fi
